name: Private Contributor Tracker

on:
  schedule:
    - cron: '15 18 * * 0'  # Every Monday at midnight Nepal Time
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          # ensure full history for safe reset/push
          persist-credentials: true

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: Sync to latest main
        run: |
          git fetch origin main
          git checkout main
          git reset --hard origin/main

      - name: List files
        run: ls -R

      - name: Run Python script
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          python3 scripts/contrib_tracker.py

      - name: Commit and push report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update weekly contribution stats [skip ci]"
            # Use force-with-lease to avoid overwriting concurrent remote changes while still allowing automatic updates
            git push origin main --force-with-lease
          fi
